# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'YSNSFoundationAdditionsExample' do
  # Example
  pod 'NSRunLoop+PerformBlock'
  pod 'twitter-text'

  target 'YSNSFoundationAdditionsExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
